app:
  build: .
  environment:
    - DISPLAY # pega a env var da maquina local
    - LC_CTYPE=en_US.UTF-8
    - LC_NUMERIC=pt_BR.UTF-8
    - LC_TIME=pt_BR.UTF-8
    - LC_COLLATE=en_US.UTF-8
    - LC_MONETARY=pt_BR.UTF-8
    - LC_MESSAGES=en_US.UTF-8
    - LC_PAPER=pt_BR.UTF-8
    - LC_NAME=pt_BR.UTF-8
    - LC_ADDRESS=pt_BR.UTF-8
    - LC_TELEPHONE=pt_BR.UTF-8
    - LC_MEASUREMENT=pt_BR.UTF-8
    - LC_IDENTIFICATION=pt_BR.UTF-8
  volumes:
    - ./ff_profile:/root/.mozilla/firefox
    - .:/data
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - $XAUTHORITY:/root/.Xauthority
  net: "host"
